### ISSUE TITLE
chown iso.nix to fix permission error after COPY

### ISSUE THREAD

**Issue by ghost** [TobiasBales/nixos-m1-arm-builder#6]
Hey thanks for this nixos builder!

When running build.sh there was a permission error so I had to chown iso.nix. Have you seen this?

output of build.sh:
```
 => [ 9/11] COPY ./iso.nix /home/nix/iso.nix                                                                   0.7s 
 => ERROR [10/11] RUN nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso.nix      1.5s 
------                                                                                                              
 > [10/11] RUN nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso.nix:                 
#14 1.146 error: opening file '/home/nix/iso.nix': Permission denied                                                
#14 1.146 (use '--show-trace' to show detailed location information)
------
executor failed running [/bin/bash -c nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso.nix]: exit code: 1
Error response from daemon: Cannot kill container: nixos-arm-builder: No such container: nixos-arm-builder
Error: No such container: nixos-arm-builder
```

fix to the Dockerfile:
```diff
diff --git Dockerfile Dockerfile
index a365202..78e9867 100644
--- Dockerfile
+++ Dockerfile
@@ -25,2 +25,3 @@ ENV NIX_PATH /home/nix/.nix-defexpr/channels
 COPY ./iso.nix /home/nix/iso.nix
+RUN sudo chown nix:nix /home/nix/iso.nix
```

**Comment by TobiasBales** [comment]
Interesting - and thanks for that!
Will merge in a minute.

I did not manage to get the install to boot into X11 (and I tried multiple DMs and WMs) - if you make it work I would love to know what I did wrong.
I also tried to switch from the minimal base image to both `graphical-gnome` and `graphical-plasma5` and both failed while building Firefox (the process gets killed during compilation for some reason I did not understand).

If you somehow get further than I did it would be lovely to update the information/let me know. I will spend some more time in the coming evenings on this.

**Comment by ghost** [comment]
I've never used NixOS but I'm using your builder to try it out. Once I figure out how to define, manage, and apply Nix configuration to the VM I can help with X11 and wayland/sway as I do have experience with that.

Are there any getting started guides you recommend for NixOS? I'm an experienced Linux user of 20 years.

**Comment by TobiasBales** [comment]
@log-to-code
I linked the official instructions in the [README](https://github.com/TobiasBales/nixos-m1-arm-builder/#install-nixos),
they worked well for me, do go the UEFI route and not MBR - that worked better for me at least.

**Comment by ghost** [comment]
Yeah, it could be a while before I get to this. I was able to build my own iso with the NixOS Manual before discovering your project so now I have VMs booting from ISOs but I need to figure out where to go from there. I need to find a guide that explains how to install packages, configure services, etc. the NixOS way.
